import type { SeedDrill } from "./seed-data";

// ---------------------------------------------------------------------------
// Batch 1 — geïnspireerd op de trainersclinic "Moves & Skills PRO"
// (Voetbalscholing.com / s.v. BLC, najaar 2025). Bewust in EIGEN woorden
// herschreven met eigen opstelling-coördinaten en pijlen (zie DOM-9: geen
// overname van externe tekst/diagrammen). Dit is een kleine proefbatch om de
// kwaliteit te beoordelen vóórdat de rest wordt omgezet.
//
// Laden met een additief script (dupliceert niet, matcht op titel):
//   npm run import-drills
// ---------------------------------------------------------------------------

export const IMPORTED_DRILLS: SeedDrill[] = [
  // 1) Warming-up — slalomdribbel met acties (Magic-7 gedachte)
  {
    title: "Slalomdribbel met acties",
    type: "WARMUP",
    theme: "NEUTRAL",
    subTheme: "Dribbelen en richtingsverandering",
    ageMin: 10,
    ageMax: 18,
    fieldType: "CIRCUIT",
    footprintX: 12,
    footprintY: 26,
    minPlayers: 6,
    idealPlayers: 10,
    maxPlayers: 16,
    durationMin: 10,
    ballScaling: "PER_PLAYER",
    description:
      "Iedere speler dribbelt in een zigzag langs de pionnen en zet vóór elke pion een actie in. Rustig starten, daarna tempo maken.",
    setup:
      "Zet vijf pionnen in een zigzag met ongeveer 6 tot 8 m ertussen. De spelers staan met een bal in een rij achter de eerste pion. Bij grote groepen twee identieke banen naast elkaar zodat er weinig wachttijd is.",
    steps: [
      "Speler A dribbelt met de bal aan de voet naar de eerste pion.",
      "Vlak vóór de pion zet A een actie in (bijv. kap met binnenkant, dan buitenkant).",
      "A dribbelt door naar de volgende pion en zet daar een andere actie in.",
      "Zo de hele slalom af; aan het eind rustig terug langs de buitenkant en achteraan aansluiten.",
      "Wissel elke ronde van actie: schaar, overstap, kapbeweging, Cruijff-draai.",
    ],
    rules: "Bal blijft dicht aan de voet; de actie wordt vóór de pion ingezet, niet erna.",
    coachingPoints:
      "Voer elke actie met beide voeten uit, zak door de knieën en houd het hoofd omhoog. Beloon een vloeiende, versnellende uitvoering na de actie.",
    progressions: "Verklein de afstand tussen de pionnen en voer het tempo op; twee acties per pion.",
    simplifications: "Grotere afstanden en één vaste, simpele actie per pion.",
    aids: [
      { type: "CONE", x: 2, y: 20 },
      { type: "CONE", x: 9, y: 16 },
      { type: "CONE", x: 2, y: 12 },
      { type: "CONE", x: 9, y: 8 },
      { type: "CONE", x: 2, y: 4 },
      { type: "PLAYER", x: 4, y: 20, label: "A" },
      { type: "BALL", x: 5.6, y: 20 },
      { type: "PLAYER", x: 4, y: 22.5 },
      { type: "PLAYER", x: 4, y: 25 },
    ],
    actions: [
      { kind: "DRIBBLE", fromX: 4, fromY: 20, toX: 9, toY: 16, label: "1 – actie bij pion" },
      { kind: "DRIBBLE", fromX: 9, fromY: 16, toX: 2, toY: 12, label: "2" },
      { kind: "DRIBBLE", fromX: 2, fromY: 12, toX: 9, toY: 8, label: "3" },
      { kind: "DRIBBLE", fromX: 9, fromY: 8, toX: 2, toY: 4, label: "4" },
    ],
  },

  // 2) Balpassing in tweetallen — aannemen en terugspelen
  {
    title: "Passen en aannemen in tweetallen",
    type: "EXERCISE",
    theme: "NEUTRAL",
    subTheme: "Passen en aannemen",
    ageMin: 10,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 16,
    footprintY: 20,
    minPlayers: 4,
    idealPlayers: 6,
    maxPlayers: 12,
    durationMin: 12,
    ballScaling: "PER_PAIR",
    description:
      "Tweetallen spelen de bal strak naar elkaar over en oefenen een zuivere aanname en pass op de voorvoeten.",
    setup:
      "Maak tweetallen die op ongeveer 10 m van elkaar staan, elk paar op een eigen lijn. Eén bal per tweetal; leg een schijfhoedje bij elke speler als vaste standplaats.",
    steps: [
      "Speler A speelt de bal over de grond in op speler B.",
      "Speler B neemt aan met de binnenkant, neemt de bal mee opzij en speelt terug op A.",
      "Herhaal en wissel de aannemende voet: eerst links, dan rechts.",
      "Variatie: één keer raken (direct terugspelen) zodra het strak en zuiver gaat.",
    ],
    rules: "Maximaal 2× raken: aannemen en spelen. Pass over de grond.",
    coachingPoints:
      "Blijf bewegen op de voorvoeten, sta open (lichaam half gedraaid) en speel op de goede voet. Aanname vóór het lichaam, niet stil laten liggen.",
    progressions: "Vergroot de afstand; neem aan met de buitenkant en draai open.",
    simplifications: "Kortere afstand en 3× raken toestaan.",
    aids: [
      { type: "DISC_CONE", x: 2, y: 3 },
      { type: "PLAYER", x: 3.5, y: 3, label: "A" },
      { type: "BALL", x: 5.2, y: 3 },
      { type: "PLAYER", x: 13, y: 3, label: "B" },
      { type: "DISC_CONE", x: 14.5, y: 3 },
      { type: "DISC_CONE", x: 2, y: 10 },
      { type: "PLAYER", x: 3.5, y: 10 },
      { type: "BALL", x: 5.2, y: 10 },
      { type: "PLAYER", x: 13, y: 10 },
      { type: "DISC_CONE", x: 14.5, y: 10 },
      { type: "DISC_CONE", x: 2, y: 17 },
      { type: "PLAYER", x: 3.5, y: 17 },
      { type: "BALL", x: 5.2, y: 17 },
      { type: "PLAYER", x: 13, y: 17 },
      { type: "DISC_CONE", x: 14.5, y: 17 },
    ],
    actions: [
      { kind: "PASS", fromX: 5.2, fromY: 3, toX: 12, toY: 3, label: "inspelen" },
      { kind: "PASS", fromX: 13, fromY: 4, toX: 4, toY: 4, label: "terug" },
    ],
  },

  // 3) Positiespel 3-1 in een vierkant
  {
    title: "Positiespel 3 tegen 1",
    type: "EXERCISE",
    theme: "ATTACK",
    subTheme: "Positiespel in opbouw verbeteren",
    ageMin: 11,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 10,
    footprintY: 10,
    minPlayers: 4,
    idealPlayers: 4,
    maxPlayers: 6,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Drie spelers houden de bal rond in een klein vierkant terwijl één verdediger probeert te onderscheppen. Denk in driehoeken.",
    setup:
      "Zet een vierkant van 8×8 m met vier pionnen. Drie aanvallers (blauw) verdelen zich over de zijden, één verdediger (oranje) staat in het midden. Eén bal.",
    steps: [
      "De baldrager heeft steeds twee afspeelmogelijkheden: speel de bal rond in een driehoek.",
      "De vrije spelers bewegen mee zodat er altijd een hoek open ligt.",
      "De verdediger jaagt en probeert te onderscheppen of de bal buiten te tikken.",
      "Bij balverovering of na 1 minuut wisselt de verdediger van rol.",
    ],
    rules: "Vrij raken, daarna terug naar maximaal 2× raken om het tempo op te voeren.",
    coachingPoints:
      "Sta ingedraaid en aanspeelbaar, speel op de verste voet en pas het baltempo aan. Loop de bal tegemoet om de pass kort te houden.",
    progressions: "Verklein het vierkant of ga naar 1× raken.",
    simplifications: "Vergroot het vierkant en speel 4 tegen 1.",
    aids: [
      { type: "CONE", x: 0, y: 0 },
      { type: "CONE", x: 10, y: 0 },
      { type: "CONE", x: 0, y: 10 },
      { type: "CONE", x: 10, y: 10 },
      { type: "PLAYER", x: 2.5, y: 2.5, label: "A" },
      { type: "BALL", x: 4, y: 2.5 },
      { type: "PLAYER", x: 7.5, y: 2.5, label: "B" },
      { type: "PLAYER", x: 2.5, y: 7.5, label: "C" },
      { type: "PLAYER_OPP", x: 5.5, y: 5.5, label: "V" },
    ],
    actions: [
      { kind: "PASS", fromX: 4, fromY: 2.5, toX: 7.5, toY: 2.5, label: "1" },
      { kind: "PASS", fromX: 7.5, fromY: 3.2, toX: 2.5, toY: 7.5, label: "2" },
    ],
  },

  // 4) 1 tegen 1 met inspeelbal en afronden op klein doel
  {
    title: "1 tegen 1 met inspeelbal",
    type: "EXERCISE",
    theme: "ATTACK",
    subTheme: "Uitspelen van één tegen één situatie verbeteren",
    ageMin: 12,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 12,
    footprintY: 16,
    minPlayers: 4,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 15,
    ballScaling: "FIXED",
    description:
      "De aanvaller wordt ingespeeld, neemt aan en probeert in een 1 tegen 1 de verdediger uit te spelen en te scoren op het kleine doel.",
    setup:
      "Klein doel aan de korte zijde. De aangever staat onderin met de ballen, de aanvaller ervoor, de verdediger tussen aanvaller en doel. De overige spelers wachten achter de aangever.",
    steps: [
      "De aangever speelt de bal in op de aanvaller (A).",
      "Op het moment van inspelen stapt de verdediger (V) in om druk te zetten.",
      "A neemt aan, maakt een actie en probeert V uit te spelen.",
      "A werkt af op het kleine doel; bij balverlies is de aanval voorbij.",
      "Doorschuiven: aangever → aanvaller → verdediger → achteraan aansluiten.",
    ],
    rules: "Weerstand 100%. Scoren mag alleen voorbij de verdediger, op het kleine doel.",
    coachingPoints:
      "Goede, ingedraaide aanname weg bij de verdediger; maak snelheid en zet de actie op het juiste moment in. Scherm de bal af met je lichaam.",
    progressions: "Voeg een tweede klein doel toe zodat A twee kanten op kan afronden.",
    simplifications: "Verdediger begint passief en zet pas na de eerste aanname vol druk.",
    aids: [
      { type: "SMALL_GOAL", x: 6, y: 1 },
      { type: "PLAYER", x: 6, y: 10, label: "A" },
      { type: "PLAYER_OPP", x: 6, y: 7, label: "V" },
      { type: "PLAYER", x: 2.5, y: 13, label: "S" },
      { type: "BALL", x: 4.1, y: 13 },
      { type: "PLAYER", x: 2.5, y: 15 },
    ],
    actions: [
      { kind: "PASS", fromX: 4.1, fromY: 13, toX: 6, toY: 10.5, label: "1 – inspelen" },
      { kind: "RUN", fromX: 6, fromY: 7, toX: 6, toY: 9, label: "druk zetten" },
      { kind: "DRIBBLE", fromX: 6, fromY: 10, toX: 3.5, toY: 4, label: "actie" },
      { kind: "SHOT", fromX: 3.5, fromY: 4, toX: 6, toY: 1.5, label: "afronden" },
    ],
  },

  // 5) Partij 4 tegen 4 met omschakelen op vier doeltjes
  {
    title: "Partij 4 tegen 4 op vier doeltjes",
    type: "MATCHFORM",
    theme: "TRANSITION",
    subTheme: "Omschakelen op moment van balverlies verbeteren",
    ageMin: 12,
    ageMax: 18,
    fieldType: "HALF",
    footprintX: 26,
    footprintY: 20,
    minPlayers: 8,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 20,
    ballScaling: "FIXED",
    description:
      "Vrije partij 4 tegen 4 waarbij elk team op twee kleine doeltjes van de tegenstander kan scoren. Nadruk op direct omschakelen bij balverlies.",
    setup:
      "Veld van ongeveer 26×20 m met aan beide korte zijden twee kleine doeltjes. Twee teams met hesjes; reserveballen bij de doeltjes zodat het spel snel doorloopt.",
    steps: [
      "Vrije partij 4 tegen 4; scoren mag op beide doeltjes van de tegenstander.",
      "Speel de bal rond en lok de tegenstander uit om het andere doeltje vrij te spelen.",
      "Bij balverlies schakelt het hele team direct om en zet druk op de bal.",
      "Bij balverovering meteen weer aanvallen en het vrije doeltje zoeken.",
    ],
    rules: "Scoren door de bal door een doeltje te spelen. Bal uit = snel inspelen door het team dat 'm niet uit speelde.",
    coachingPoints:
      "Houd het tempo hoog en wissel van kant; het moment van balverlies bepaalt het duel — reageer als eerste. Coach elkaar bij het omschakelen.",
    progressions: "Maximaal 3× raken; voeg een neutrale speler toe voor het balbezittende team.",
    simplifications: "Groter veld en vrij aantal keren raken voor meer rust aan de bal.",
    aids: [
      { type: "SMALL_GOAL", x: 7, y: 1 },
      { type: "SMALL_GOAL", x: 19, y: 1 },
      { type: "SMALL_GOAL", x: 7, y: 19 },
      { type: "SMALL_GOAL", x: 19, y: 19 },
      // Blauw team (valt naar boven aan)
      { type: "PLAYER", x: 6, y: 13, label: "A" },
      { type: "PLAYER", x: 20, y: 13 },
      { type: "PLAYER", x: 11, y: 16 },
      { type: "PLAYER", x: 16, y: 16 },
      { type: "BALL", x: 12, y: 12 },
      // Oranje team (valt naar beneden aan)
      { type: "PLAYER_OPP", x: 6, y: 7 },
      { type: "PLAYER_OPP", x: 20, y: 7 },
      { type: "PLAYER_OPP", x: 11, y: 4 },
      { type: "PLAYER_OPP", x: 16, y: 4 },
    ],
    actions: [
      { kind: "PASS", fromX: 11, fromY: 16, toX: 6, toY: 13, label: "rondspelen" },
      { kind: "RUN", fromX: 16, fromY: 16, toX: 18, toY: 11, label: "vrijlopen" },
    ],
  },

  // ===== Batch 2 — brede dekking van de clinic (gededupliceerd) ==============

  // 6) Coördinatieladder met afsluitende pass
  {
    title: "Coördinatieladder met afsluitende pass",
    type: "WARMUP",
    theme: "CONDITIE",
    subTheme: "Coördinatie en wendbaarheid",
    ageMin: 10,
    ageMax: 18,
    fieldType: "CIRCUIT",
    footprintX: 10,
    footprintY: 18,
    minPlayers: 4,
    idealPlayers: 8,
    maxPlayers: 16,
    durationMin: 8,
    ballScaling: "FIXED",
    description:
      "Voetenwerk door de loopladder, direct gevolgd door een pass en terugkaats met een medespeler. Motoriek en handelingssnelheid combineren.",
    setup:
      "Leg een loopladder neer met een aangever (B) enkele meters achter de ladder. De rest wacht in een rij vóór de ladder. Eén bal bij de aangever.",
    steps: [
      "Speler A gaat met snelle voeten door de ladder (bijv. dubbele pas).",
      "Direct uit de ladder speelt B de bal in op A.",
      "A kaatst in één keer terug en sluit achteraan weer aan.",
      "Wissel de laddervorm en de aannemende voet elke ronde.",
    ],
    rules: "Uit de ladder pas versnellen; de kaats gaat in één keer terug.",
    coachingPoints:
      "Op de voorvoeten, actieve armen en een rechte romp. Let na de ladder op de draairichting zodat A snel kan anticiperen op de pass.",
    progressions: "Kaats afwisselend met links en rechts; voeg een tweede ladder haaks toe.",
    simplifications: "Enkele pas door de ladder en een rustige aanname vóór het terugspelen.",
    aids: [
      { type: "MARKER", x: 2.6, y: 3, label: "ladder" },
      { type: "MARKER", x: 4, y: 3 },
      { type: "MARKER", x: 2.6, y: 4.4 },
      { type: "MARKER", x: 4, y: 4.4 },
      { type: "MARKER", x: 2.6, y: 5.8 },
      { type: "MARKER", x: 4, y: 5.8 },
      { type: "MARKER", x: 2.6, y: 7.2 },
      { type: "MARKER", x: 4, y: 7.2 },
      { type: "MARKER", x: 2.6, y: 8.6 },
      { type: "MARKER", x: 4, y: 8.6 },
      { type: "PLAYER", x: 3.3, y: 11, label: "A" },
      { type: "PLAYER", x: 3.3, y: 13 },
      { type: "PLAYER", x: 3.3, y: 15 },
      { type: "PLAYER", x: 7.5, y: 4, label: "B" },
      { type: "BALL", x: 7.5, y: 5.7 },
    ],
    actions: [
      { kind: "RUN", fromX: 3.3, fromY: 10, toX: 3.3, toY: 3, label: "1 – ladder" },
      { kind: "PASS", fromX: 7.5, fromY: 4, toX: 3.6, toY: 3, label: "2 – inspelen" },
      { kind: "PASS", fromX: 3.6, fromY: 3.6, toX: 7.3, toY: 4.4, label: "3 – kaats" },
    ],
  },

  // 7) Startsnelheid met eerste pass
  {
    title: "Startsnelheid met eerste pass",
    type: "WARMUP",
    theme: "CONDITIE",
    subTheme: "Snelheid en acceleratie",
    ageMin: 11,
    ageMax: 19,
    fieldType: "CIRCUIT",
    footprintX: 9,
    footprintY: 16,
    minPlayers: 4,
    idealPlayers: 8,
    maxPlayers: 14,
    durationMin: 8,
    ballScaling: "FIXED",
    description:
      "Explosieve start met een korte sprint, gevolgd door een inspeelbal die in één keer wordt teruggelegd. Nadruk op de eerste passen.",
    setup:
      "Zet drie pionnen op een rechte lijn met korte, oplopende afstanden. Aangever (B) staat schuin vooraan met een bal. De rest wacht achter de startpion.",
    steps: [
      "Speler A start op teken explosief langs de pionnen.",
      "Bij de laatste pion speelt B de bal in.",
      "A legt de bal in één keer terug en jogt terug om aan te sluiten.",
      "Volledige rust tussen de herhalingen; kwaliteit boven kwantiteit.",
    ],
    rules: "De eerste pas is naast de pion, voorwaarts — niet naar achteren.",
    coachingPoints:
      "Lage, krachtige eerste passen en actieve armzwaai. De afzet bepaalt de versnelling; houd het lichaam licht voorover.",
    progressions: "Start vanuit een liggende of zittende houding; reageer op een visueel teken.",
    simplifications: "Kortere sprint en een rustige terugpass.",
    aids: [
      { type: "CONE", x: 4, y: 12 },
      { type: "CONE", x: 4, y: 9 },
      { type: "CONE", x: 4, y: 6 },
      { type: "PLAYER", x: 4, y: 13.5, label: "A" },
      { type: "PLAYER", x: 4, y: 15.6 },
      { type: "PLAYER", x: 6.5, y: 3, label: "B" },
      { type: "BALL", x: 6.5, y: 4.7 },
    ],
    actions: [
      { kind: "RUN", fromX: 4, fromY: 13, toX: 4, toY: 6, label: "1 – sprint" },
      { kind: "PASS", fromX: 6.5, fromY: 3.4, toX: 4.3, toY: 5.6, label: "2 – inspelen" },
      { kind: "PASS", fromX: 4.3, fromY: 5.6, toX: 6.3, toY: 3.4, label: "3 – terug" },
    ],
  },

  // 8) Frontale actie tegen komende tegenstander
  {
    title: "Frontale actie in het midden",
    type: "EXERCISE",
    theme: "NEUTRAL",
    subTheme: "Dribbelen en richtingsverandering",
    ageMin: 11,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 12,
    footprintY: 14,
    minPlayers: 4,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 10,
    ballScaling: "PER_PLAYER",
    description:
      "Twee spelers dribbelen diagonaal naar het midden en zetten daar een frontale actie (schaar of overstap) in vóór ze doorgaan.",
    setup:
      "Zet een schijfhoedje in het midden en vier startpunten in de hoeken. Twee spelers starten tegelijk vanuit tegenoverliggende hoeken, elk met een bal.",
    steps: [
      "Speler A en B dribbelen diagonaal naar het middenpunt.",
      "In het midden zet ieder een frontale actie in (eerst linkerbeen, dan rechterbeen over de bal).",
      "Na de actie dribbelen ze door naar de vrije hoek schuin tegenover.",
      "De volgende twee spelers starten; wissel per ronde van actie.",
    ],
    rules: "De actie wordt precies in het midden ingezet, met de juiste timing zodat de spelers elkaar niet raken.",
    coachingPoints:
      "Bal kort aan de voet, door de knieën zakken en na de schijnbeweging versnellen. Voer de actie met beide benen uit.",
    progressions: "Twee acties achter elkaar; verhoog het tempo.",
    simplifications: "Eén simpele kapbeweging in plaats van een frontale actie.",
    aids: [
      { type: "DISC_CONE", x: 6, y: 7 },
      { type: "PLAYER", x: 3, y: 3, label: "A" },
      { type: "BALL", x: 4.6, y: 3 },
      { type: "PLAYER", x: 9, y: 3, label: "B" },
      { type: "BALL", x: 7.4, y: 3 },
      { type: "DISC_CONE", x: 3, y: 11 },
      { type: "DISC_CONE", x: 9, y: 11 },
    ],
    actions: [
      { kind: "DRIBBLE", fromX: 3, fromY: 3, toX: 9, toY: 11, label: "1 – actie in het midden" },
      { kind: "DRIBBLE", fromX: 9, fromY: 3, toX: 3, toY: 11, label: "2" },
    ],
  },

  // 9) Schaarbeweging inslijpen
  {
    title: "Schaarbeweging inslijpen",
    type: "WARMUP",
    theme: "NEUTRAL",
    subTheme: "Balgewenning en baltechniek",
    ageMin: 9,
    ageMax: 15,
    fieldType: "CIRCUIT",
    footprintX: 12,
    footprintY: 9,
    minPlayers: 4,
    idealPlayers: 8,
    maxPlayers: 14,
    durationMin: 8,
    ballScaling: "PER_PLAYER",
    description:
      "Rustige leervorm voor de schaarbeweging: draai om de bal en neem hem met de buitenkant mee opzij.",
    setup:
      "Zet tweetallen tegenover elkaar met één pion ertussen. Iedere speler heeft een bal en oefent bij de pion.",
    steps: [
      "Draai met de linkervoet van binnen naar buiten om de bal.",
      "Neem de bal daarna met de buitenkant rechts mee naar buiten.",
      "Je staat nu een kwartslag gedraaid; doe de beweging andersom terug.",
      "Eerst vanuit stilstand, daarna vanuit een lichte dribbel.",
    ],
    rules: "Bal blijft dicht bij de voet; inslijpen tot het vloeiend gaat.",
    coachingPoints:
      "Kleine, snelle voeten en overtuigende schijnbeweging met het bovenlichaam. Doe de beweging met beide benen.",
    progressions: "Voer de schaar uit vanuit een dribbel en versnel na de actie.",
    simplifications: "Alleen de draaibeweging zonder meenemen, tot het ritme erin zit.",
    aids: [
      { type: "PLAYER", x: 3, y: 2.5, label: "A" },
      { type: "BALL", x: 4.6, y: 2.5 },
      { type: "CONE", x: 6, y: 2.5 },
      { type: "PLAYER", x: 9, y: 2.5, label: "B" },
      { type: "BALL", x: 7.4, y: 2.5 },
      { type: "PLAYER", x: 3, y: 6.5 },
      { type: "BALL", x: 4.6, y: 6.5 },
      { type: "CONE", x: 6, y: 6.5 },
      { type: "PLAYER", x: 9, y: 6.5 },
      { type: "BALL", x: 7.4, y: 6.5 },
    ],
    actions: [
      { kind: "DRIBBLE", fromX: 4.6, fromY: 2.5, toX: 5.6, toY: 1.4, label: "schaar" },
    ],
  },

  // 10) Harmonica passen
  {
    title: "Harmonica passen",
    type: "EXERCISE",
    theme: "NEUTRAL",
    subTheme: "Passen en aannemen",
    ageMin: 11,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 16,
    footprintY: 10,
    minPlayers: 4,
    idealPlayers: 6,
    maxPlayers: 10,
    durationMin: 10,
    ballScaling: "FIXED",
    description:
      "Spelers passen de bal als een harmonica van links naar rechts door de rij, aannemen en doorspelen op de voorvoeten.",
    setup:
      "Zet de spelers in een licht zigzaggende rij met ongeveer 4 m ertussen. Eén bal begint bij de buitenste speler.",
    steps: [
      "Speler A speelt in op B; B neemt aan en speelt door op C.",
      "Zo schuift de bal de hele rij door en weer terug.",
      "Open gaan staan zodat je met de buitenste voet aanneemt en met de andere doorspeelt.",
      "Variatie: één keer raken zodra het strak gaat.",
    ],
    rules: "Maximaal 2× raken; pass strak over de grond.",
    coachingPoints:
      "Denk aan de lichaamshouding: sta open in de oefening en neem aan op de verste voet. Nauwkeurigheid boven snelheid.",
    progressions: "Eén keer raken; voeg een tweede bal vanaf de andere kant toe.",
    simplifications: "Kortere afstanden en 3× raken.",
    aids: [
      { type: "PLAYER", x: 2, y: 4, label: "A" },
      { type: "BALL", x: 3.6, y: 4 },
      { type: "PLAYER", x: 6, y: 2, label: "B" },
      { type: "PLAYER", x: 9, y: 6, label: "C" },
      { type: "PLAYER", x: 13, y: 3, label: "D" },
    ],
    actions: [
      { kind: "PASS", fromX: 3.6, fromY: 4, toX: 6, toY: 2, label: "1" },
      { kind: "PASS", fromX: 6, fromY: 2, toX: 9, toY: 6, label: "2" },
      { kind: "PASS", fromX: 9, fromY: 6, toX: 13, toY: 3, label: "3" },
    ],
  },

  // 11) 1-2 combinatie met druk
  {
    title: "1-2 combinatie met druk",
    type: "EXERCISE",
    theme: "ATTACK",
    subTheme: "Positiespel in opbouw verbeteren",
    ageMin: 12,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 14,
    footprintY: 16,
    minPlayers: 4,
    idealPlayers: 6,
    maxPlayers: 10,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Vaste 1-2 combinatie waarbij telkens een speler licht druk zet, zodat kaatsen onder een beetje weerstand wordt geoefend.",
    setup:
      "Vier posities in een ruit met schijfhoedjes: A onderin met de bal, B en D aan de zijkanten als kaatsers, C bovenin. Overige spelers wachten achter A.",
    steps: [
      "Speler A speelt in op B; C zet licht druk.",
      "B maakt een 1-2 met A en speelt de bal door op D.",
      "A schuift door en zet nu op zijn beurt druk bij D.",
      "Doorschuiven van posities; wissel van kaatser.",
    ],
    rules: "Kaatsen in één keer; de druk is eerst passief, daarna half.",
    coachingPoints:
      "Nauwkeurig inspelen op de goede voet en snel wisselen van kaatsen naar druk zetten. Blijf aanspeelbaar door hoekjes te maken.",
    progressions: "Volle druk op de kaatser; kortere afstanden.",
    simplifications: "Zonder druk; alleen de 1-2 inslijpen.",
    aids: [
      { type: "DISC_CONE", x: 3, y: 13 },
      { type: "PLAYER", x: 4.5, y: 13, label: "A" },
      { type: "BALL", x: 6.1, y: 13 },
      { type: "DISC_CONE", x: 3, y: 8 },
      { type: "PLAYER", x: 4.5, y: 8, label: "B" },
      { type: "DISC_CONE", x: 8, y: 4 },
      { type: "PLAYER_OPP", x: 9.5, y: 6, label: "C" },
      { type: "DISC_CONE", x: 11, y: 9 },
      { type: "PLAYER", x: 11, y: 11, label: "D" },
    ],
    actions: [
      { kind: "PASS", fromX: 6.1, fromY: 13, toX: 4.5, toY: 8.6, label: "1" },
      { kind: "RUN", fromX: 9.5, fromY: 6, toX: 5.5, toY: 8, label: "druk" },
      { kind: "PASS", fromX: 4.5, fromY: 8.6, toX: 5.4, toY: 12.4, label: "2 – kaats" },
      { kind: "PASS", fromX: 5.4, fromY: 12.4, toX: 11, toY: 11, label: "3" },
    ],
  },

  // 12) Passen met wegdraaien
  {
    title: "Passen met wegdraaien",
    type: "EXERCISE",
    theme: "NEUTRAL",
    subTheme: "Passen en aannemen",
    ageMin: 11,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 14,
    footprintY: 10,
    minPlayers: 4,
    idealPlayers: 6,
    maxPlayers: 12,
    durationMin: 10,
    ballScaling: "PER_PAIR",
    description:
      "Bij de aanname draait de speler weg met de bal (open of achterlangs) voordat hij terugspeelt. Oefent het opendraaien onder controle.",
    setup:
      "Tweetallen op ongeveer 10 m van elkaar, elk met een bal en een schijfhoedje als draaipunt achter de aannemende speler.",
    steps: [
      "Speler A speelt in op B.",
      "B draait met de bal weg om het schijfhoedje (open draaien of onder de voetzool terug).",
      "B dribbelt kort in en speelt de bal terug op A.",
      "Wissel de draairichting en herhaal; daarna van rol wisselen.",
    ],
    rules: "Vóór het inspelen omhoog en vooruit kijken; bal dicht bij het lichaam houden bij het draaien.",
    coachingPoints:
      "Maak jezelf sterk met een splitstep vóór de aanname en zak licht door de knieën, dan draait het makkelijker. Minimale, strakke draai.",
    progressions: "Draai in één beweging weg en speel direct terug; volle snelheid.",
    simplifications: "Groter draaipunt en een rustige, losse aanname.",
    aids: [
      { type: "PLAYER", x: 3, y: 3, label: "A" },
      { type: "BALL", x: 4.6, y: 3 },
      { type: "PLAYER", x: 11, y: 3, label: "B" },
      { type: "DISC_CONE", x: 12.6, y: 3 },
      { type: "PLAYER", x: 3, y: 7 },
      { type: "BALL", x: 4.6, y: 7 },
      { type: "PLAYER", x: 11, y: 7 },
      { type: "DISC_CONE", x: 12.6, y: 7 },
    ],
    actions: [
      { kind: "PASS", fromX: 4.6, fromY: 3, toX: 10, toY: 3, label: "1 – inspelen" },
      { kind: "DRIBBLE", fromX: 11, fromY: 3, toX: 11.8, toY: 4, label: "2 – wegdraaien" },
      { kind: "PASS", fromX: 10.6, fromY: 3.6, toX: 4, toY: 3.6, label: "3 – terug" },
    ],
  },

  // 13) Passestervorm met doordraaien
  {
    title: "Passestervorm met doordraaien",
    type: "EXERCISE",
    theme: "NEUTRAL",
    subTheme: "Passen en aannemen",
    ageMin: 12,
    ageMax: 19,
    fieldType: "QUARTER",
    footprintX: 16,
    footprintY: 16,
    minPlayers: 6,
    idealPlayers: 6,
    maxPlayers: 12,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Passvorm in een ster/ruit waarbij spelers na hun pass doorschuiven, met tussendoor een 1-2. Overzicht en zuiver inspelen.",
    setup:
      "Zes posities met schijfhoedjes in een ruit met twee middenspelers. Eén bal; bij grotere groepen een tweede bal toevoegen.",
    steps: [
      "Speler A maakt een 1-2 met de dichtstbijzijnde middenspeler.",
      "A speelt de bal door naar de volgende buitenpositie.",
      "Iedereen schuift een positie door in de looprichting van de bal.",
      "Na enkele minuten de andere kant op en met de andere voet.",
    ],
    rules: "Maximaal 2× raken; de 1-2 gaat in één keer.",
    coachingPoints:
      "Sta ingedraaid, kies vooraf je vervolgactie en pas de lengte van de pass aan. Beweeg naar de bal toe.",
    progressions: "Voeg een tweede bal toe; speel op 1× raken.",
    simplifications: "Zonder 1-2: alleen passen en je pass volgen.",
    aids: [
      { type: "DISC_CONE", x: 8, y: 14.8 },
      { type: "PLAYER", x: 8, y: 13, label: "A" },
      { type: "BALL", x: 9.5, y: 13 },
      { type: "DISC_CONE", x: 2.3, y: 10 },
      { type: "PLAYER", x: 4, y: 10, label: "B" },
      { type: "DISC_CONE", x: 2.3, y: 6 },
      { type: "PLAYER", x: 4, y: 6, label: "C" },
      { type: "DISC_CONE", x: 8, y: 0.8 },
      { type: "PLAYER", x: 8, y: 2.5, label: "D" },
      { type: "DISC_CONE", x: 13.7, y: 6 },
      { type: "PLAYER", x: 12, y: 6, label: "E" },
      { type: "DISC_CONE", x: 13.7, y: 10 },
      { type: "PLAYER", x: 12, y: 10, label: "F" },
    ],
    actions: [
      { kind: "PASS", fromX: 9.5, fromY: 13, toX: 4.6, toY: 10, label: "1" },
      { kind: "PASS", fromX: 4.6, fromY: 10, toX: 4.6, toY: 6, label: "2" },
      { kind: "PASS", fromX: 4.6, fromY: 6, toX: 8, toY: 3, label: "3" },
    ],
  },

  // 14) Aanvalsvorm met dubbele 1-2 en afronden
  {
    title: "Dubbele 1-2 en afronden",
    type: "EXERCISE",
    theme: "ATTACK",
    subTheme: "Creëren van kansen",
    ageMin: 13,
    ageMax: 19,
    fieldType: "QUARTER",
    footprintX: 22,
    footprintY: 30,
    minPlayers: 6,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 15,
    ballScaling: "FIXED",
    description:
      "Snelle passcombinatie over meerdere schijven met twee 1-2's, afgerond op doel. Handelingssnelheid en timing van de afronding.",
    setup:
      "Groot doel met keeper. Vier posities met schijfhoedjes: A onderin met de ballen, B links, C rechts als kaatsers, D centraal voor het doel. Wachtrij achter A.",
    steps: [
      "Speler A maakt een 1-2 met B.",
      "A speelt door op C; C legt terug op de ingelopen D.",
      "D speelt de diepte in op de opkomende A.",
      "A neemt mee en werkt af op doel; posities doorschuiven.",
    ],
    rules: "Kaatsen in één keer; afronden in maximaal 2 contacten.",
    coachingPoints:
      "Kies het juiste moment voor de overloop zonder bal en blijf geconcentreerd bij de afronding. Baltempo hoog houden.",
    progressions: "Voeg een passieve verdediger bij D toe.",
    simplifications: "Speel de laatste bal in de voeten in plaats van in de diepte.",
    aids: [
      { type: "BIG_GOAL", x: 11, y: 1.2 },
      { type: "PLAYER", x: 11, y: 3.4, label: "K" },
      { type: "PLAYER", x: 10, y: 25, label: "A" },
      { type: "BALL", x: 11.6, y: 25 },
      { type: "PLAYER", x: 10, y: 27 },
      { type: "PLAYER", x: 10, y: 29 },
      { type: "DISC_CONE", x: 8, y: 25 },
      { type: "PLAYER", x: 5, y: 19, label: "B" },
      { type: "DISC_CONE", x: 3, y: 19 },
      { type: "PLAYER", x: 17, y: 17, label: "C" },
      { type: "DISC_CONE", x: 19, y: 17 },
      { type: "PLAYER", x: 11, y: 11, label: "D" },
      { type: "DISC_CONE", x: 13, y: 11 },
    ],
    actions: [
      { kind: "PASS", fromX: 11.6, fromY: 25, toX: 5, toY: 19, label: "1" },
      { kind: "PASS", fromX: 5, fromY: 19, toX: 10, toY: 24, label: "2 – kaats" },
      { kind: "PASS", fromX: 10, fromY: 24, toX: 17, toY: 17, label: "3" },
      { kind: "PASS", fromX: 17, fromY: 17, toX: 11, toY: 11, label: "4 – terug" },
      { kind: "PASS", fromX: 11, fromY: 11, toX: 12, toY: 20, label: "5 – diep" },
      { kind: "SHOT", fromX: 12, fromY: 12, toX: 11, toY: 3.6, label: "afronden" },
    ],
  },

  // 15) Aanvalsvorm met twee vaste kaatsers
  {
    title: "Aanvalsvorm met twee vaste kaatsers",
    type: "EXERCISE",
    theme: "ATTACK",
    subTheme: "Positiespel in opbouw verbeteren",
    ageMin: 13,
    ageMax: 19,
    fieldType: "QUARTER",
    footprintX: 22,
    footprintY: 30,
    minPlayers: 6,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 15,
    ballScaling: "FIXED",
    description:
      "Opbouw met twee vaste kaatsers (B en D) die blijven staan, waarna via een terugleg­bal wordt afgerond op doel.",
    setup:
      "Groot doel met keeper. B en D staan als vaste kaatsers centraal; A start onderin met de bal, C is de vrije speler. Wachtrij achter A.",
    steps: [
      "Speler A speelt in op kaatser B; B legt breed op de vrijlopende C.",
      "C dribbelt voorwaarts en speelt op kaatser D.",
      "D legt de bal breed op de opkomende A.",
      "A werkt af op doel; B en D blijven staan, de rest schuift door.",
    ],
    rules: "Kaatsers spelen in één keer; loopacties zonder bal goed timen.",
    coachingPoints:
      "Bewaar overzicht en kijk waar de medespelers staan; nauwkeurig inspelen op de goede voet. Opkomen op het juiste moment.",
    progressions: "Voeg een tweede afmaker toe op de tweede paal.",
    simplifications: "Grotere afstanden en een rustige, hoge afronding toestaan.",
    aids: [
      { type: "BIG_GOAL", x: 11, y: 1.2 },
      { type: "PLAYER", x: 11, y: 3.4, label: "K" },
      { type: "PLAYER", x: 5, y: 25, label: "A" },
      { type: "BALL", x: 6.6, y: 25 },
      { type: "PLAYER", x: 5, y: 27 },
      { type: "PLAYER", x: 5, y: 29 },
      { type: "DISC_CONE", x: 3, y: 25 },
      { type: "PLAYER", x: 9, y: 18, label: "B" },
      { type: "DISC_CONE", x: 9, y: 20 },
      { type: "PLAYER", x: 16, y: 20, label: "C" },
      { type: "DISC_CONE", x: 18, y: 20 },
      { type: "PLAYER", x: 13, y: 11, label: "D" },
      { type: "DISC_CONE", x: 13, y: 13 },
    ],
    actions: [
      { kind: "PASS", fromX: 6.6, fromY: 25, toX: 9, toY: 18.6, label: "1" },
      { kind: "PASS", fromX: 9, fromY: 18.6, toX: 16, toY: 20, label: "2 – breed" },
      { kind: "PASS", fromX: 16, fromY: 20, toX: 13, toY: 11.6, label: "3" },
      { kind: "PASS", fromX: 13, fromY: 11.6, toX: 8, toY: 18, label: "4 – breed" },
      { kind: "SHOT", fromX: 8, fromY: 17, toX: 11, toY: 3.6, label: "afronden" },
    ],
  },

  // 16) Opbouw met teruglegbal en voorzet
  {
    title: "Teruglegbal en voorzet afronden",
    type: "EXERCISE",
    theme: "ATTACK",
    subTheme: "Creëren van kansen",
    ageMin: 13,
    ageMax: 19,
    fieldType: "QUARTER",
    footprintX: 22,
    footprintY: 30,
    minPlayers: 6,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 15,
    ballScaling: "FIXED",
    description:
      "Opbouw via een uitzakkende spits en een terugleg­bal, gevolgd door een dieptepass en voorzet die wordt afgerond.",
    setup:
      "Groot doel met keeper. A onderin met de bal, B centraal-mid, C uitzakkende spits, D vleugelspeler rechts. Wachtrij achter A.",
    steps: [
      "Speler A speelt in op B; B op de uitzakkende C.",
      "C legt de bal terug op B.",
      "B speelt de diepte in op de opkomende D op de vleugel.",
      "D geeft een lage voorzet die C in de zestien afrondt.",
    ],
    rules: "Voorzet laag en hard, achter de laatste verdediger; afronden in één contact.",
    coachingPoints:
      "Goede timing van de terugleg en de inloop; kom van achteren op de voorzet. Baltempo aanpassen aan de loopactie.",
    progressions: "Voeg een verdediger bij C toe; afronden in maximaal 2 contacten.",
    simplifications: "Hogere, langzamere voorzet en een controle vóór het afronden.",
    aids: [
      { type: "BIG_GOAL", x: 11, y: 1.2 },
      { type: "PLAYER", x: 11, y: 3.4, label: "K" },
      { type: "PLAYER", x: 6, y: 26, label: "A" },
      { type: "BALL", x: 7.6, y: 26 },
      { type: "PLAYER", x: 6, y: 28 },
      { type: "DISC_CONE", x: 4, y: 26 },
      { type: "PLAYER", x: 8, y: 20, label: "B" },
      { type: "DISC_CONE", x: 6, y: 20 },
      { type: "PLAYER", x: 11, y: 14, label: "C" },
      { type: "DISC_CONE", x: 13, y: 14 },
      { type: "PLAYER", x: 18, y: 18, label: "D" },
      { type: "DISC_CONE", x: 20, y: 18 },
    ],
    actions: [
      { kind: "PASS", fromX: 7.6, fromY: 26, toX: 8, toY: 20.6, label: "1" },
      { kind: "PASS", fromX: 8, fromY: 20, toX: 11, toY: 14.6, label: "2" },
      { kind: "PASS", fromX: 11, fromY: 14.6, toX: 8.6, toY: 20, label: "3 – terug" },
      { kind: "PASS", fromX: 8.6, fromY: 20, toX: 18, toY: 18, label: "4 – diep" },
      { kind: "PASS", fromX: 18, fromY: 17, toX: 11, toY: 8, label: "5 – voorzet" },
      { kind: "SHOT", fromX: 11, fromY: 8, toX: 11, toY: 3.6, label: "afronden" },
    ],
  },

  // 17) 2 tegen 2 met kleine doeltjes
  {
    title: "2 tegen 2 met kleine doeltjes",
    type: "MATCHFORM",
    theme: "TRANSITION",
    subTheme: "Omschakelen bij veroveren van de bal verbeteren",
    ageMin: 11,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 15,
    footprintY: 15,
    minPlayers: 4,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Klein partijtje 2 tegen 2 op twee kleine doeltjes, met veel duels en snelle omschakeling bij balverlies.",
    setup:
      "Veld van ongeveer 15×15 m met aan weerszijden een klein doeltje. Twee tweetallen met hesjes; reserveballen bij de doeltjes.",
    steps: [
      "Spelen 2 tegen 2; scoren op het doeltje van de tegenstander.",
      "De baldrager kiest tussen een individuele actie en overspelen.",
      "De speler zonder bal maakt een loopactie om ruimte te creëren.",
      "Bij balverlies direct omschakelen en druk zetten; wissel de tweetallen regelmatig.",
    ],
    rules: "Snel doorwisselen van tweetallen; scoren alleen door het doeltje.",
    coachingPoints:
      "Kijk om je heen waar de ruimte ligt; de loopactie kan misleidend zijn. Wees de eerste bij het omschakelen.",
    progressions: "Speel er een tweede 2 tegen 2 in dezelfde ruimte doorheen als extra weerstand.",
    simplifications: "Groter veld voor meer tijd en ruimte aan de bal.",
    aids: [
      { type: "SMALL_GOAL", x: 7.5, y: 1 },
      { type: "SMALL_GOAL", x: 7.5, y: 14 },
      { type: "PLAYER", x: 5, y: 10, label: "A" },
      { type: "BALL", x: 6.6, y: 10 },
      { type: "PLAYER", x: 10, y: 10, label: "B" },
      { type: "PLAYER_OPP", x: 5, y: 5 },
      { type: "PLAYER_OPP", x: 10, y: 5 },
    ],
    actions: [
      { kind: "PASS", fromX: 6.6, fromY: 10, toX: 10, toY: 10, label: "overspelen" },
      { kind: "RUN", fromX: 10, fromY: 10, toX: 8, toY: 5.5, label: "vrijlopen" },
    ],
  },

  // 18) 1 tegen 1 met omschakelen op twee doeltjes
  {
    title: "1 tegen 1 met omschakelen",
    type: "MATCHFORM",
    theme: "TRANSITION",
    subTheme: "Omschakelen op moment van balverlies verbeteren",
    ageMin: 11,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 12,
    footprintY: 14,
    minPlayers: 4,
    idealPlayers: 8,
    maxPlayers: 12,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Duel 1 tegen 1 waarbij de aanvaller na scoren of balverlies meteen verdediger wordt op het andere doeltje. Constant omschakelen.",
    setup:
      "Twee kleine doeltjes tegenover elkaar. De aanvaller start met de bal in het midden, de verdediger ervoor. Wachtrijen aan de zijkant.",
    steps: [
      "De aanvaller (A) probeert de verdediger (V) uit te spelen en te scoren.",
      "Na een doelpunt of bij balverlies schakelt A om en verdedigt het andere doeltje.",
      "De volgende speler brengt direct een nieuwe bal in het spel.",
      "Tempo hoog houden; wissel de rollen regelmatig.",
    ],
    rules: "Meteen omschakelen bij scoren of balverlies; scoren op het kleine doeltje.",
    coachingPoints:
      "Maak snelheid en zet je actie op het juiste moment in; bij balverlies direct de kortste weg terug naar je doeltje.",
    progressions: "Beide spelers mogen op twee doeltjes scoren.",
    simplifications: "Verdediger begint passief; groter veld.",
    aids: [
      { type: "SMALL_GOAL", x: 6, y: 1 },
      { type: "SMALL_GOAL", x: 6, y: 13 },
      { type: "PLAYER", x: 6, y: 9, label: "A" },
      { type: "BALL", x: 7.6, y: 9 },
      { type: "PLAYER_OPP", x: 6, y: 6, label: "V" },
      { type: "PLAYER", x: 1.5, y: 11 },
      { type: "PLAYER_OPP", x: 10.5, y: 4 },
    ],
    actions: [
      { kind: "DRIBBLE", fromX: 6, fromY: 9, toX: 4, toY: 4, label: "actie" },
      { kind: "SHOT", fromX: 4, fromY: 4, toX: 6, toY: 1.5, label: "scoren" },
      { kind: "RUN", fromX: 6, fromY: 6, toX: 6, toY: 12, label: "omschakelen" },
    ],
  },

  // 19) 2 tegen 1 uitspelen
  {
    title: "2 tegen 1 uitspelen",
    type: "EXERCISE",
    theme: "ATTACK",
    subTheme: "Uitspelen van één tegen één situatie verbeteren",
    ageMin: 11,
    ageMax: 18,
    fieldType: "QUARTER",
    footprintX: 12,
    footprintY: 16,
    minPlayers: 3,
    idealPlayers: 9,
    maxPlayers: 12,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Overtalsituatie 2 tegen 1 richting een klein doel: kiezen tussen zelf doorgaan of de vrije medespeler benutten.",
    setup:
      "Klein doel aan de korte zijde. Twee aanvallers starten onderin, één verdediger ervoor. Wachtrijen achter de startpunten.",
    steps: [
      "Speler A speelt samen met B en probeert verdediger V uit te spelen.",
      "De vrije speler maakt een goede hoek om aanspeelbaar te zijn.",
      "Scoren op het kleine doel voorbij de verdediger.",
      "Doorwisselen van spelers en rollen.",
    ],
    rules: "Bij balverlies is de aanval voorbij; snel doorwisselen.",
    coachingPoints:
      "De baldrager houdt de verdediger in twijfel; de loopactie van de vrije speler kan misleidend zijn. Tempo hoog houden.",
    progressions: "Verklein het veld of maak er 2 tegen 2 van.",
    simplifications: "Verdediger begint passief en zet pas laat druk.",
    aids: [
      { type: "SMALL_GOAL", x: 6, y: 1 },
      { type: "PLAYER", x: 4, y: 12, label: "A" },
      { type: "BALL", x: 5.6, y: 12 },
      { type: "PLAYER", x: 9, y: 12, label: "B" },
      { type: "PLAYER_OPP", x: 6, y: 7, label: "V" },
      { type: "PLAYER", x: 4, y: 14 },
      { type: "PLAYER", x: 9, y: 14 },
    ],
    actions: [
      { kind: "PASS", fromX: 5.6, fromY: 12, toX: 9, toY: 12, label: "1" },
      { kind: "RUN", fromX: 4, fromY: 12, toX: 5, toY: 5, label: "meelopen" },
      { kind: "SHOT", fromX: 9, fromY: 11, toX: 6, toY: 1.5, label: "scoren" },
    ],
  },

  // 20) 4 tegen 4 plus neutralen
  {
    title: "4 tegen 4 met neutrale spelers",
    type: "MATCHFORM",
    theme: "ATTACK",
    subTheme: "Positiespel in opbouw verbeteren",
    ageMin: 13,
    ageMax: 19,
    fieldType: "HALF",
    footprintX: 26,
    footprintY: 20,
    minPlayers: 10,
    idealPlayers: 12,
    maxPlayers: 16,
    durationMin: 20,
    ballScaling: "FIXED",
    description:
      "Partij 4 tegen 4 met vaste neutrale spelers die altijd met de balbezittende partij meespelen, zodat er in overtal wordt opgebouwd.",
    setup:
      "Veld met aan beide korte zijden een klein doel. Twee teams van vier met hesjes; enkele neutrale spelers (N) op de zijlijnen en in het midden spelen met de aanvallende partij mee.",
    steps: [
      "Spelen 4 tegen 4; de neutrale spelers doen mee met wie de bal heeft.",
      "Gebruik het overtal om rustig op te bouwen en de bal diep in te spelen.",
      "Lok de tegenstander uit met rondspelen en wissel van kant.",
      "Bij balverlies schakelen de neutralen mee om en steunen de nieuwe balbezitter.",
    ],
    rules: "Neutralen spelen altijd mee met de balbezittende partij; scoren op een klein doel.",
    coachingPoints:
      "Speel de bal diep in en sluit snel bij; tempo hoog houden. Maak het veld breed in balbezit.",
    progressions: "Maximaal 3× raken; profiteer alleen op de helft van de tegenstander.",
    simplifications: "Extra neutrale speler of vrij aantal keren raken.",
    aids: [
      { type: "SMALL_GOAL", x: 13, y: 1 },
      { type: "SMALL_GOAL", x: 13, y: 19 },
      { type: "PLAYER", x: 8, y: 13, label: "A" },
      { type: "PLAYER", x: 18, y: 13 },
      { type: "PLAYER", x: 11, y: 16 },
      { type: "PLAYER", x: 15, y: 16 },
      { type: "PLAYER_OPP", x: 8, y: 7 },
      { type: "PLAYER_OPP", x: 18, y: 7 },
      { type: "PLAYER_OPP", x: 11, y: 4 },
      { type: "PLAYER_OPP", x: 15, y: 4 },
      { type: "PLAYER", x: 2, y: 10, label: "N" },
      { type: "PLAYER", x: 24, y: 10, label: "N" },
      { type: "PLAYER", x: 13, y: 10, label: "N" },
      { type: "BALL", x: 14.6, y: 10 },
    ],
    actions: [
      { kind: "PASS", fromX: 13, fromY: 10, toX: 8, toY: 13, label: "1" },
      { kind: "PASS", fromX: 8, fromY: 13, toX: 2, toY: 10, label: "2 – breed" },
    ],
  },

  // 21) Partijvorm met wisselend aantal spelers
  {
    title: "Partijvorm met wisselend aantal",
    type: "MATCHFORM",
    theme: "TRANSITION",
    subTheme: "Omschakelen bij veroveren van de bal verbeteren",
    ageMin: 12,
    ageMax: 19,
    fieldType: "HALF",
    footprintX: 24,
    footprintY: 18,
    minPlayers: 6,
    idealPlayers: 10,
    maxPlayers: 16,
    durationMin: 18,
    ballScaling: "FIXED",
    description:
      "De trainer speelt de bal in en roept een getal; dat aantal spelers per team komt het veld in voor een partijtje. Snelle reactie en omschakeling.",
    setup:
      "Veld met aan beide korte zijden een klein doel. Beide teams wachten in de hoeken. De trainer staat aan de zijkant met een voorraad ballen.",
    steps: [
      "De trainer speelt de bal in het veld en roept een getal (bijv. 2).",
      "Dat aantal spelers per team sprint het veld in en speelt de partij uit.",
      "Wie het eerst bij de bal is valt aan, de ander verdedigt.",
      "Na een doelpunt of bal uit een nieuwe bal en een nieuw getal.",
    ],
    rules: "Alleen het gevraagde aantal spelers per team; scoren op het kleine doel.",
    coachingPoints:
      "Speel op de anticipatie: reageer als eerste op de inspeelbal. Dwing acties af en schakel direct om bij balverlies.",
    progressions: "Roep wisselende getallen snel achter elkaar; meerdere situaties tegelijk.",
    simplifications: "Vast aantal (2 tegen 2) en een rustiger tempo.",
    aids: [
      { type: "SMALL_GOAL", x: 12, y: 1 },
      { type: "SMALL_GOAL", x: 12, y: 17 },
      { type: "PLAYER_OPP", x: 3, y: 3 },
      { type: "PLAYER_OPP", x: 3, y: 5 },
      { type: "PLAYER_OPP", x: 21, y: 3 },
      { type: "PLAYER_OPP", x: 21, y: 5 },
      { type: "PLAYER", x: 3, y: 15 },
      { type: "PLAYER", x: 3, y: 13 },
      { type: "PLAYER", x: 21, y: 15 },
      { type: "PLAYER", x: 21, y: 13 },
      { type: "PLAYER", x: 12, y: 9, label: "T" },
      { type: "BALL", x: 13.6, y: 9 },
    ],
    actions: [
      { kind: "PASS", fromX: 12, fromY: 9, toX: 12, toY: 12, label: "inspelen" },
    ],
  },

  // 22) Positiespel 5 tegen 2 met omschakelen
  {
    title: "Positiespel 5 tegen 2 met omschakelen",
    type: "EXERCISE",
    theme: "TRANSITION",
    subTheme: "Omschakelen op moment van balverlies verbeteren",
    ageMin: 12,
    ageMax: 19,
    fieldType: "QUARTER",
    footprintX: 16,
    footprintY: 11,
    minPlayers: 7,
    idealPlayers: 7,
    maxPlayers: 12,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Vijftal houdt de bal rond tegen twee verdedigers; bij balverovering spelen de verdedigers de bal snel naar het andere vak, waar wordt omgeschakeld.",
    setup:
      "Zet een vak van ongeveer 15×10 m met pionnen (in de praktijk twee vakken naast elkaar). Vijf spelers (blauw) tegen twee verdedigers (oranje). Eén bal.",
    steps: [
      "Het vijftal speelt de bal rond en probeert de twee verdedigers uit te spelen.",
      "De baldrager zoekt steeds twee afspeelmogelijkheden (driehoek).",
      "Bij balverovering spelen de verdedigers de bal snel naar het andere vak.",
      "Daar wordt direct omgeschakeld: nieuwe verdedigers jagen.",
    ],
    rules: "Van 2× raken naar 1× raken; omschakelen bij balverlies.",
    coachingPoints:
      "Sta ingedraaid en aanspeelbaar; de handelingssnelheid gaat omhoog als de ruimte kleiner wordt. Coach elkaar bij het omschakelen.",
    progressions: "Verklein het vak of speel op 1× raken; voeg een verdediger toe.",
    simplifications: "Groter vak en 3× raken toestaan.",
    aids: [
      { type: "CONE", x: 0, y: 0 },
      { type: "CONE", x: 15, y: 0 },
      { type: "CONE", x: 0, y: 10 },
      { type: "CONE", x: 15, y: 10 },
      { type: "PLAYER", x: 2.5, y: 2, label: "A" },
      { type: "BALL", x: 4.1, y: 2 },
      { type: "PLAYER", x: 12.5, y: 2, label: "B" },
      { type: "PLAYER", x: 2.5, y: 8, label: "C" },
      { type: "PLAYER", x: 12.5, y: 8, label: "D" },
      { type: "PLAYER", x: 7.5, y: 5, label: "E" },
      { type: "PLAYER_OPP", x: 5.5, y: 4 },
      { type: "PLAYER_OPP", x: 10, y: 6.5 },
    ],
    actions: [
      { kind: "PASS", fromX: 4.1, fromY: 2, toX: 7.5, toY: 5, label: "1" },
      { kind: "PASS", fromX: 7.5, fromY: 5, toX: 12.5, toY: 8, label: "2" },
    ],
  },

  // 23) Positiespel 6 tegen 3 met omschakelen
  {
    title: "Positiespel 6 tegen 3",
    type: "EXERCISE",
    theme: "TRANSITION",
    subTheme: "Omschakelen bij veroveren van de bal verbeteren",
    ageMin: 13,
    ageMax: 19,
    fieldType: "QUARTER",
    footprintX: 12,
    footprintY: 20,
    minPlayers: 9,
    idealPlayers: 9,
    maxPlayers: 12,
    durationMin: 12,
    ballScaling: "FIXED",
    description:
      "Twee groepjes van drie proberen elkaar te bereiken langs drie verdedigers in het midden. Geduld in balbezit en compact verdedigen.",
    setup:
      "Veld van ongeveer 10×20 m. Drie aanvallers (blauw) aan elke korte zijde, drie verdedigers (oranje) in het middenvak. Eén bal.",
    steps: [
      "De drie aanvallers spelen de bal rond en zoeken het moment om de drie in het midden te bereiken.",
      "De drie verdedigers verdedigen compact en proberen te onderscheppen.",
      "Lukt de pass naar de overkant, dan is het weer 3 tegen 3 daar.",
      "Wissel de verdedigers na een aantal onderscheppingen.",
    ],
    rules: "In balbezit het baltempo omhoog; geduld tot er een gaatje valt.",
    coachingPoints:
      "Speel breed en snel rond om het gaatje te forceren; verdedigers blijven compact en coachen elkaar.",
    progressions: "Beperk het aantal keren raken; maak het vak smaller.",
    simplifications: "Groter vak of een verdediger minder.",
    aids: [
      { type: "CONE", x: 0, y: 0 },
      { type: "CONE", x: 10, y: 0 },
      { type: "CONE", x: 0, y: 20 },
      { type: "CONE", x: 10, y: 20 },
      { type: "PLAYER", x: 2, y: 3, label: "A" },
      { type: "BALL", x: 3.5, y: 3.5 },
      { type: "PLAYER", x: 5, y: 2.5, label: "B" },
      { type: "PLAYER", x: 8, y: 3, label: "C" },
      { type: "PLAYER", x: 2, y: 17 },
      { type: "PLAYER", x: 5, y: 17.5 },
      { type: "PLAYER", x: 8, y: 17 },
      { type: "PLAYER_OPP", x: 3, y: 10 },
      { type: "PLAYER_OPP", x: 7, y: 10 },
      { type: "PLAYER_OPP", x: 5, y: 13 },
    ],
    actions: [
      { kind: "PASS", fromX: 3.5, fromY: 3.5, toX: 8, toY: 3, label: "1 – rondspelen" },
      { kind: "PASS", fromX: 8, fromY: 3.6, toX: 8, toY: 16.6, label: "2 – diep" },
    ],
  },

  // 24) Positiespel 4 tegen 1
  {
    title: "Positiespel 4 tegen 1",
    type: "EXERCISE",
    theme: "NEUTRAL",
    subTheme: "Positiespel en balbezit",
    ageMin: 10,
    ageMax: 18,
    fieldType: "CIRCUIT",
    footprintX: 10,
    footprintY: 10,
    minPlayers: 5,
    idealPlayers: 5,
    maxPlayers: 8,
    durationMin: 10,
    ballScaling: "FIXED",
    description:
      "Rondo 4 tegen 1 in een klein vierkant: bal rondspelen met steeds twee afspeel­mogelijkheden en van 2× raken naar 1× raken.",
    setup:
      "Vierkant van ongeveer 10×10 m met vier pionnen. Vier spelers op de zijden, één verdediger in het midden. Eén bal.",
    steps: [
      "De baldrager heeft altijd twee opties: speel de bal rond langs de zijden.",
      "Sta ingedraaid en aanspeelbaar zodat je meteen kunt doorspelen.",
      "De verdediger jaagt en probeert te onderscheppen.",
      "Ga van 2× raken over naar 1× raken; wissel de verdediger na een onderschepping.",
    ],
    rules: "Blijf op de zijden van het vierkant; de verdediger mag overal komen.",
    coachingPoints:
      "Speel op de verste voet en houd het baltempo hoog; de handelingssnelheid gaat omhoog als het vierkant kleiner wordt.",
    progressions: "Verklein het vierkant of ga naar 6 tegen 2 in een groter vak.",
    simplifications: "Groter vierkant en 2× raken.",
    aids: [
      { type: "CONE", x: 0, y: 0 },
      { type: "CONE", x: 10, y: 0 },
      { type: "CONE", x: 0, y: 10 },
      { type: "CONE", x: 10, y: 10 },
      { type: "PLAYER", x: 5, y: 2, label: "A" },
      { type: "BALL", x: 6.6, y: 2 },
      { type: "PLAYER", x: 8, y: 5, label: "B" },
      { type: "PLAYER", x: 5, y: 8, label: "C" },
      { type: "PLAYER", x: 2, y: 5, label: "D" },
      { type: "PLAYER_OPP", x: 5, y: 5, label: "V" },
    ],
    actions: [
      { kind: "PASS", fromX: 6.6, fromY: 2, toX: 8, toY: 5, label: "1" },
      { kind: "PASS", fromX: 8, fromY: 5, toX: 5, toY: 8, label: "2" },
    ],
  },
];
